### PR TITLE
fix: #211;

### LINKED ISSUE #211: Make "copyEmptyDirectories = false" optional
[Here](https://github.com/anatawa12/ForgeGradle-1.2/blob/9f771fde8633b396daa9cc69a2ab383c0ea4d2f4/src/main/java/net/minecraftforge/gradle/tasks/user/reobf/ObfArtifact.java#L371) forgegradle sets copyEmptyDirectories to false that causes SpecialSource not add directory entries to obfuscated jar, this causes getResource to return null on folders in mods (for example, WarpDrive checks if directory exists with getResource [here](https://github.com/LemADEC/WarpDrive/blob/90abf4fcde95537419275a2beb30fc8ec3fbb27b/src/main/java/cr0s/warpdrive/block/TileEntityAbstractInterfaced.java#L103))

### PR DESCRIPTION
**Pull request by MJaroslav**
Just made `copyEmptyDirectories` optional (also added getter and setter in tasks with it).

I tested it with `reobf` task when use package relocate (like as #151):
```gradle
tasks.getByName("reobf").doFirst {
    setCopyEmptyDirectories(true);
}
```
All tasks that use remapper, but i not tested this with all of it :woozy_face::
- `reobf`
- `deobfBinJar`
- `deobfuscateJar`

### CODE REVIEW

File: src/main/java/net/minecraftforge/gradle/extrastuff/ReobfExceptor.java [hunk 1]
```diff
@@ -24,6 +24,7 @@ public class ReobfExceptor {
     public File methodCSV;
     public File fieldCSV;
     public File excConfig;
+    public boolean copyEmptyDirectories; // Only for SpecialSource
```
Comment (anatawa12) [inline src/main/java/net/minecraftforge/gradle/extrastuff/ReobfExceptor.java]: I don't like to add `copyEmptyDirectories` here. I think adding `copyEmptyDirectories` parameter to `ObfArtifact.generate` is better.

**Review by anatawa12 — CHANGES_REQUESTED** [review]
Thank you for contribution and sorry for late response.

**Review by anatawa12 — APPROVED** [review]
LGTM! Thank you for implementing this feature!

**Comment by MJaroslav** [comment]
In any case, it's my fault that this was necessary in general :woozy_face:
